/* Synthetic example items. Mod lines come from poe2_kb_0.5.5.json; the header format follows
 * master prompt 5.2. Affix names ("Summoner's" etc.) are left out because the knowledge base has none.
 * Replace with real game copies when available (open questions 1 and 9). */
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.PoE2Samples = api;
})(typeof self !== 'undefined' ? self : this, function () {
  const D = '—';
  return [
    {
      id: 'rare-sceptre-adv',
      label: 'Rare sceptre · Alt+Ctrl+C',
      text: [
        'Item Class: Sceptres',
        'Rarity: Rare',
        'Doom Song',
        'Rattling Sceptre',
        '--------',
        'Spirit: 100',
        '--------',
        'Requires: Level 78, 104 Int',
        '--------',
        'Item Level: 82',
        '--------',
        `{ Prefix Modifier (Tier: 1) ${D} Mana }`,
        '+152(150-164) to maximum Mana',
        `{ Prefix Modifier (Tier: 1) }`,
        '63(61-65)% increased Spirit',
        `{ Suffix Modifier (Tier: 2) ${D} Minion, Gem }`,
        '+3 to Level of all Minion Skills',
        `{ Suffix Modifier (Tier: 2) ${D} Minion, Life }`,
        'Minions have 43(41-45)% increased maximum Life',
      ].join('\n'),
    },
    {
      id: 'magic-helmet-plain',
      label: 'Magic helmet · Ctrl+C',
      text: [
        'Item Class: Helmets',
        'Rarity: Magic',
        'Masked Greathelm',
        '--------',
        'Armour: 180',
        '--------',
        'Requires: Level 70, 101 Str',
        '--------',
        'Item Level: 79',
        '--------',
        '+2 to Level of all Minion Skills',
      ].join('\n'),
    },
    {
      id: 'magic-flask',
      label: 'Magic life flask · Alt+Ctrl+C',
      text: [
        'Item Class: Life Flasks',
        'Rarity: Magic',
        'Careful Ultimate Life Flask of the Eternal',
        '--------',
        'Recovers 920 Life over 3 Seconds',
        'Consumes 10 of 75 Charges on use',
        'Currently has 75 Charges',
        '--------',
        'Requires: Level 60',
        '--------',
        'Item Level: 84',
        '--------',
        '{ Prefix Modifier "Careful" (Tier: 2) }',
        '85(81-90)% more Recovery if used while on Low Life',
        '{ Suffix Modifier "of the Eternal" (Tier: 1) }',
        '65(63-70)% increased Charges gained',
      ].join('\n'),
    },
    {
      id: 'rare-boots-fractured',
      label: 'Rare boots · fractured',
      text: [
        'Item Class: Boots',
        'Rarity: Rare',
        'Gale Stride',
        'Totemic Greaves',
        '--------',
        'Armour: 120',
        '--------',
        'Item Level: 81',
        '--------',
        `{ Fractured Prefix Modifier (Tier: 2) ${D} Speed }`,
        '30% increased Movement Speed',
        `{ Prefix Modifier (Tier: 1) ${D} Life }`,
        '+131(120-149) to maximum Life',
        `{ Suffix Modifier (Tier: 2) ${D} Elemental, Cold, Resistance }`,
        '+38(36-40)% to Cold Resistance',
        `{ Suffix Modifier (Tier: 1) ${D} Elemental, Resistance }`,
        '57(56-60)% reduced Freeze Duration on you',
        '--------',
        'Fractured Item',
      ].join('\n'),
    },
    {
      id: 'rare-helmet-desecrated',
      label: 'Rare helmet · desecrated + crafted',
      text: [
        'Item Class: Helmets',
        'Rarity: Rare',
        'Rune Crown',
        'Masked Greathelm',
        '--------',
        'Item Level: 80',
        '--------',
        `{ Prefix Modifier (Tier: 1) ${D} Life }`,
        '+160(150-174) to maximum Life',
        `{ Suffix Modifier (Tier: 1) ${D} Minion, Gem }`,
        '+2 to Level of all Minion Skills',
        `{ Desecrated Suffix Modifier }`,
        '6(4-8)% increased Spirit Reservation Efficiency of Skills',
        `{ Suffix Modifier ${D} Elemental, Fire, Resistance }`,
        '+39(36-40)% to Fire Resistance',
      ].join('\n'),
    },
    {
      id: 'rare-amulet-corrupted',
      label: 'Rare amulet · corrupted',
      text: [
        'Item Class: Amulets',
        'Rarity: Rare',
        'Grim Charm',
        'Bloodstone Amulet',
        '--------',
        'Requires: Level 60',
        '--------',
        'Item Level: 76',
        '--------',
        `{ Implicit Modifier ${D} Life }`,
        '+35(30-40) to maximum Life',
        '--------',
        `{ Suffix Modifier (Tier: 1) ${D} Minion, Gem }`,
        '+3 to Level of all Minion Skills',
        `{ Prefix Modifier (Tier: 1) ${D} Spirit }`,
        '+48(47-50) to Spirit',
        `{ Suffix Modifier (Tier: 2) ${D} Elemental, Resistance }`,
        '+16(15-16)% to all Elemental Resistances',
        '--------',
        'Corrupted',
      ].join('\n'),
    },
    {
      id: 'rare-amulet-plain',
      label: 'Rare amulet · Ctrl+C',
      text: [
        'Item Class: Amulets',
        'Rarity: Rare',
        'Storm Locket',
        'Bloodstone Amulet',
        '--------',
        'Item Level: 81',
        '--------',
        '+33 to maximum Life (implicit)',
        '--------',
        '+128 to maximum Life',
        '17% increased Rarity of Items found',
        '+38% to Fire Resistance',
        '+3 to Level of all Minion Skills (fractured)',
      ].join('\n'),
    },
    {
      id: 'unrevealed',
      label: 'Unrevealed desecrated',
      text: [
        'Item Class: Rings',
        'Rarity: Rare',
        'Glyph Loop',
        'Gold Ring',
        '--------',
        'Item Level: 78',
        '--------',
        `{ Prefix Modifier ${D} Life }`,
        '+95(90-104) to maximum Life',
        `{ Desecrated Suffix Modifier }`,
        'Unrevealed Desecrated Modifier',
      ].join('\n'),
    },
  ];
});
